apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - name: udagram-api-user
        image: lucasilvestrelivero/udagram-api-user
        ports:
        - containerPort: 8080